config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pl/ do
    resources :members do
      get :search, on: :collection
    end
    devise_for :users
    root 'members#index'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_a? Admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < User
end

app/models/member.rb
class Member < User
  attr_accessor :skip_password_validation

  belongs_to :parent_1, class_name: 'Member', foreign_key: 'parent_1', optional: true
  belongs_to :parent_2, class_name: 'Member', foreign_key: 'parent_2', optional: true

  def to_s
    "#{first_name} #{last_name}"
  end

  def parents
    [ parent_1, parent_2 ].compact
  end

  def children
    User.where(parent_1: id).or(User.where(parent_2: id))
  end

  def siblings
    User.where(parent_1: parents).or(User.where(parent_2: parents)).where.not(id: id)
  end

  def self.search(q)
    where "first_name LIKE ? OR last_name LIKE ?", "%#{q}%", "%#{q}%"
  end

  protected

    def password_required?
      return false if skip_password_validation
      super
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :email, :type
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_locale

  def default_url_options
    { locale: I18n.locale }
  end


  private

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  load_and_authorize_resource
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /members
  # GET /members.json
  def index
    @members = Member.all.paginate(page: params[:page]).order(sort_column + " " + sort_direction)
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @member.skip_password_validation = true

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @q = params['q']
    @members = Member.search @q
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:email, :first_name, :last_name, :sex, :birthdate, :address, :phone_number)
    end

    def sort_column
      Member.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def glyphicon(name)
    content_tag(:span, '', class: "glyphicon glyphicon-#{name}") + ' '
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyTree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Family Tree', root_url, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <% if signed_in? %>
            <ul class="nav navbar-nav">
              <li class="<%= 'active' if I18n.locale == :pl %>"><%= link_to('pl', locale: :pl) %></li>
              <li class="<%= 'active' if I18n.locale == :en %>"><%= link_to('en', locale: :en) %></li>
            </ul>
            <ul class="nav navbar-nav navbar-left">
              <li style="margin-left: 90px">
                <%= form_tag search_members_path, method: :get, class: 'navbar-form' do |f| %>
                  <div class="input-group">
                    <%= text_field_tag :q, params['q'], class: 'form-control input-sm', placeholder: 'Szukaj...', required: true %>
                    <span class="input-group-btn">
                      <%= button_tag (glyphicon :search), type: :submit, class: 'btn btn-default btn-sm', title: 'Szukaj', name: nil, data: { disable_with: glyphicon(:hourglass) } %>
                    </span>
                  </div>
                <% end %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Wyloguj', destroy_user_session_path, method: :delete %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/_form.html.haml
= form_for @member, url: member_path(I18n.locale, @member) do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :sex
    = f.text_field :sex
  .field
    = f.label :birthdate
    = f.date_select :birthdate
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .actions
    = f.submit 'Save'

app/views/members/_member.haml
%tr
  %td= link_to member, member
  %td= member.sex
  %td= member.birthdate.strftime("%d/%m/%Y")
  %td= "#{(Time.now.year - member.birthdate.year)} y"
  %td= member.address
  %td= member.phone_number

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', member_path(I18n.locale, @member)
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
%h1 Listing members

%table.table.table-striped.table-hover
  %thead
    %tr
      %th= sortable 'last_name', t('activerecord.attributes.member.name')
      %th= t 'activerecord.attributes.member.sex'
      %th= t 'activerecord.attributes.member.age'
      %th= t 'activerecord.attributes.member.birthdate'
      %th= t 'activerecord.attributes.member.address'
      %th= t 'activerecord.attributes.member.phone_number'

  %tbody
    = render partial: 'member', collection: @members, as: :member

= link_to 'New Member', new_member_path, class: 'btn btn-success' if can?(:create, Member)

= will_paginate @members

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/search.haml
%h2.page-header Wyszkiwanie '#{@q}'

%h5.page-header
  Wyniki
  %span.badge{title: 'Ilość'}= @members.count
- if @members.any?
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th= t 'activerecord.attributes.member.name'
        %th= t 'activerecord.attributes.member.sex'
        %th= t 'activerecord.attributes.member.age'
        %th= t 'activerecord.attributes.member.birthdate'
        %th= t 'activerecord.attributes.member.address'
        %th= t 'activerecord.attributes.member.phone_number'

    %tbody
      = render partial: 'member', collection: @members
- else
  %em Brak wyników.

app/views/members/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @member.email
%p
  %b First name:
  = @member.first_name
%p
  %b Last name:
  = @member.last_name
%p
  %b Sex:
  = @member.sex
%p
  %b Birthdate:
  = @member.birthdate
%p
  %b Address:
  = @member.address
%p
  %b Phone number:
  = @member.phone_number

%h4 Parents
%p= link_to_if @member.parent_1, @member.parent_1, @member.parent_1
%p= link_to_if @member.parent_2, @member.parent_2, @member.parent_2

%h4 Children
%table.table.table-striped.table-hover
  %thead
    %tr
      %th= t 'activerecord.attributes.member.name'
      %th= t 'activerecord.attributes.member.sex'
      %th= t 'activerecord.attributes.member.age'
      %th= t 'activerecord.attributes.member.birthdate'
      %th= t 'activerecord.attributes.member.address'
      %th= t 'activerecord.attributes.member.phone_number'

  %tbody
    = render partial: 'member', collection: @member.children, as: :member

%h4 Siblings
%table.table.table-striped.table-hover
  %thead
    %tr
      %th= t 'activerecord.attributes.member.name'
      %th= t 'activerecord.attributes.member.sex'
      %th= t 'activerecord.attributes.member.age'
      %th= t 'activerecord.attributes.member.birthdate'
      %th= t 'activerecord.attributes.member.address'
      %th= t 'activerecord.attributes.member.phone_number'

  %tbody
    = render partial: 'member', collection: @member.siblings, as: :member 

%br

= link_to 'Back', members_path, class: 'btn btn-default'
= link_to 'Edit', edit_member_path(@member), class: 'btn btn-warning' if can?(:edit, @member)